[INFO] [2025-04-05 13:48:02,544] - main: App Started
[INFO] [2025-04-05 13:48:02,714] - database: Connected to database was successfull
[INFO] [2025-04-05 13:48:04,786] - pages: 'Start' page was openned
[INFO] [2025-04-05 13:51:14,687] - main: App Started
[INFO] [2025-04-05 13:51:14,769] - database: Connected to database was successfull
[INFO] [2025-04-05 13:51:15,158] - pages: 'Start' page was openned
[INFO] [2025-04-06 21:23:54,771] - main: App Started
[INFO] [2025-04-06 21:23:54,952] - database: Connected to database was successfull
[INFO] [2025-04-06 21:23:56,605] - pages: 'Start' page was openned
[INFO] [2025-04-15 11:36:34,131] - main: App Started
[INFO] [2025-04-15 11:36:34,203] - database: Connected to database was successfull
[INFO] [2025-04-15 11:36:35,454] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:47:53,908] - main: App Started
[INFO] [2025-04-15 11:47:54,097] - database: Connected to database was successfull
[INFO] [2025-04-15 11:47:54,564] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:48:35,353] - main: App Started
[INFO] [2025-04-15 11:48:35,429] - database: Connected to database was successfull
[INFO] [2025-04-15 11:48:35,812] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:48:55,597] - main: App Started
[INFO] [2025-04-15 11:48:55,649] - database: Connected to database was successfull
[INFO] [2025-04-15 11:48:56,081] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:49:29,783] - main: App Started
[INFO] [2025-04-15 11:49:30,010] - database: Connected to database was successfull
[INFO] [2025-04-15 11:49:30,477] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:49:49,796] - main: App Started
[INFO] [2025-04-15 11:49:49,885] - database: Connected to database was successfull
[INFO] [2025-04-15 11:49:50,297] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:50:16,186] - main: App Started
[INFO] [2025-04-15 11:50:16,260] - database: Connected to database was successfull
[INFO] [2025-04-15 11:50:16,664] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:50:31,775] - main: App Started
[INFO] [2025-04-15 11:50:31,849] - database: Connected to database was successfull
[INFO] [2025-04-15 11:50:32,391] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:51:03,845] - main: App Started
[INFO] [2025-04-15 11:51:03,942] - database: Connected to database was successfull
[INFO] [2025-04-15 11:51:04,480] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:52:05,705] - main: App Started
[INFO] [2025-04-15 11:52:05,839] - database: Connected to database was successfull
[INFO] [2025-04-15 11:52:06,289] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:53:07,339] - main: App Started
[INFO] [2025-04-15 11:53:07,535] - database: Connected to database was successfull
[INFO] [2025-04-15 11:53:07,959] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:53:37,190] - main: App Started
[INFO] [2025-04-15 11:53:37,266] - database: Connected to database was successfull
[INFO] [2025-04-15 11:53:37,689] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:53:52,543] - main: App Started
[INFO] [2025-04-15 11:53:52,618] - database: Connected to database was successfull
[INFO] [2025-04-15 11:53:53,014] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 11:54:40,493] - main: App Started
[INFO] [2025-04-15 11:54:40,711] - database: Connected to database was successfull
[INFO] [2025-04-15 11:54:41,137] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:04:58,179] - main: App Started
[INFO] [2025-04-15 12:04:58,399] - database: Connected to database was successfull
[INFO] [2025-04-15 12:04:58,845] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:06:04,334] - main: App Started
[INFO] [2025-04-15 12:06:04,534] - database: Connected to database was successfull
[INFO] [2025-04-15 12:06:04,922] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:06:41,546] - main: App Started
[INFO] [2025-04-15 12:06:41,626] - database: Connected to database was successfull
[INFO] [2025-04-15 12:06:42,026] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:09:21,583] - main: App Started
[INFO] [2025-04-15 12:09:21,657] - database: Connected to database was successfull
[INFO] [2025-04-15 12:09:22,050] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:09:49,965] - main: App Started
[INFO] [2025-04-15 12:09:50,185] - database: Connected to database was successfull
[INFO] [2025-04-15 12:09:50,602] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:10:46,623] - main: App Started
[INFO] [2025-04-15 12:10:46,851] - database: Connected to database was successfull
[INFO] [2025-04-15 12:10:47,279] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:12:01,302] - main: App Started
[INFO] [2025-04-15 12:12:01,378] - database: Connected to database was successfull
[INFO] [2025-04-15 12:12:01,795] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 12:12:22,691] - pages: 'Start' page was openned
[INFO] [2025-04-15 12:52:22,192] - main: App Started
[INFO] [2025-04-15 12:52:22,346] - database: Connected to database was successfull
[INFO] [2025-04-15 12:52:22,987] - pages: 'StartAdmin' page was openned
[ERROR] [2025-04-15 12:52:41,545] - asyncio: Future exception was never retrieved
future: <Future finished exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\core\page.py", line 903, in wrapper
    handler(*args)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Desktop\pages.py", line 491, in backPage
    start_page(self.page,True)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Desktop\pages.py", line 441, in start_page
    with open("Admin Configure", 'r') as File:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Admin Configure'
[INFO] [2025-04-15 13:26:03,325] - main: App Started
[INFO] [2025-04-15 13:26:03,465] - database: Connected to database was successfull
[INFO] [2025-04-15 13:26:04,029] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 13:28:11,494] - main: App Started
[INFO] [2025-04-15 13:28:11,546] - database: Connected to database was successfull
[INFO] [2025-04-15 13:28:12,024] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 13:30:59,907] - main: App Started
[INFO] [2025-04-15 13:30:59,960] - database: Connected to database was successfull
[INFO] [2025-04-15 13:31:00,458] - pages: 'StartAdmin' page was openned
[ERROR] [2025-04-15 13:31:44,391] - database: Request execute was failed. Reason: ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "administators_pkey"
DETAIL:  Ключ "(login)=(who)" уже существует.

[ERROR] [2025-04-15 13:31:44,968] - asyncio: Future exception was never retrieved
future: <Future finished exception=Exception('Request execute was failed')>
Traceback (most recent call last):
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 31, in reqExecute
    cursor.execute(request)
psycopg2.errors.UniqueViolation: ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "administators_pkey"
DETAIL:  Ключ "(login)=(who)" уже существует.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\core\page.py", line 903, in wrapper
    handler(*args)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Desktop\pages.py", line 500, in adminRegInBD
    bd.reqExecute(f"Insert into Administators(FSL,Login, Password, TG_Username) values ('{fslField.value}', '{loginField.value}', '{passwordField.value}', '{usernameField.value}')")
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 44, in reqExecute
    raise Exception("Request execute was failed")
Exception: Request execute was failed
[INFO] [2025-04-15 13:33:44,949] - main: App Started
[INFO] [2025-04-15 13:33:45,110] - database: Connected to database was successfull
[INFO] [2025-04-15 13:33:45,603] - pages: 'StartAdmin' page was openned
[INFO] [2025-04-15 13:35:57,849] - main: App Started
[INFO] [2025-04-15 13:35:57,910] - database: Connected to database was successfull
[INFO] [2025-04-15 13:36:06,067] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:36:55,304] - main: App Started
[INFO] [2025-04-15 13:36:55,355] - database: Connected to database was successfull
[INFO] [2025-04-15 13:37:29,464] - main: App Started
[INFO] [2025-04-15 13:37:29,517] - database: Connected to database was successfull
[INFO] [2025-04-15 13:37:54,780] - main: App Started
[INFO] [2025-04-15 13:37:54,971] - database: Connected to database was successfull
[INFO] [2025-04-15 13:39:00,271] - main: App Started
[INFO] [2025-04-15 13:39:00,323] - database: Connected to database was successfull
[INFO] [2025-04-15 13:39:04,559] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:39:11,238] - main: App Started
[INFO] [2025-04-15 13:39:11,463] - database: Connected to database was successfull
[INFO] [2025-04-15 13:39:34,903] - main: App Started
[INFO] [2025-04-15 13:39:35,074] - database: Connected to database was successfull
[INFO] [2025-04-15 13:39:52,012] - main: App Started
[INFO] [2025-04-15 13:39:52,065] - database: Connected to database was successfull
[INFO] [2025-04-15 13:39:58,755] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:40:17,661] - main: App Started
[INFO] [2025-04-15 13:40:17,827] - database: Connected to database was successfull
[INFO] [2025-04-15 13:40:18,371] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:40:37,455] - main: App Started
[INFO] [2025-04-15 13:40:37,510] - database: Connected to database was successfull
[INFO] [2025-04-15 13:40:37,927] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:41:23,400] - main: App Started
[INFO] [2025-04-15 13:41:23,452] - database: Connected to database was successfull
[INFO] [2025-04-15 13:41:23,927] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:41:56,260] - main: App Started
[INFO] [2025-04-15 13:41:56,311] - database: Connected to database was successfull
[INFO] [2025-04-15 13:41:56,743] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:42:57,270] - main: App Started
[INFO] [2025-04-15 13:42:57,340] - database: Connected to database was successfull
[INFO] [2025-04-15 13:42:57,770] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:45:53,922] - main: App Started
[INFO] [2025-04-15 13:45:53,974] - database: Connected to database was successfull
[INFO] [2025-04-15 13:45:54,418] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:46:16,431] - main: App Started
[INFO] [2025-04-15 13:46:16,483] - database: Connected to database was successfull
[INFO] [2025-04-15 13:46:16,938] - pages: 'Start' page was openned
[INFO] [2025-04-15 13:47:18,026] - main: App Started
[INFO] [2025-04-15 13:47:18,091] - database: Connected to database was successfull
[INFO] [2025-04-15 13:47:18,591] - pages: 'Start' page was openned
[INFO] [2025-04-15 15:02:20,221] - main: App Started
[INFO] [2025-04-15 15:02:20,272] - database: Connected to database was successfull
[INFO] [2025-04-15 15:02:20,786] - pages: 'Start' page was openned
[INFO] [2025-04-15 16:39:50,379] - main: App Started
[INFO] [2025-04-15 16:39:50,532] - database: Connected to database was successfull
[INFO] [2025-04-15 16:41:04,884] - main: App Started
[INFO] [2025-04-15 16:41:05,103] - database: Connected to database was successfull
[INFO] [2025-04-15 16:41:05,820] - pages: 'Start' page was openned
[ERROR] [2025-04-15 16:41:18,978] - asyncio: Future exception was never retrieved
future: <Future finished exception=UnsupportedOperation('not readable')>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\core\page.py", line 903, in wrapper
    handler(*args)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\utilits_desktop.py", line 184, in pageClose
    for line in file:
io.UnsupportedOperation: not readable
[INFO] [2025-04-15 16:42:08,172] - main: App Started
[INFO] [2025-04-15 16:42:08,232] - database: Connected to database was successfull
[INFO] [2025-04-15 16:42:08,702] - pages: 'Start' page was openned
[ERROR] [2025-04-15 16:42:37,323] - asyncio: Future exception was never retrieved
future: <Future finished exception=ValueError('I/O operation on closed file.')>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\core\page.py", line 903, in wrapper
    handler(*args)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\utilits_desktop.py", line 184, in pageClose
    for line in file:
ValueError: I/O operation on closed file.
[INFO] [2025-04-15 16:44:18,212] - main: App Started
[INFO] [2025-04-15 16:44:18,262] - database: Connected to database was successfull
[INFO] [2025-04-15 16:44:18,717] - pages: 'Start' page was openned
[INFO] [2025-04-15 16:44:32,001] - main: App Started
[INFO] [2025-04-15 16:44:32,187] - database: Connected to database was successfull
[INFO] [2025-04-15 16:44:48,190] - main: App Started
[INFO] [2025-04-15 16:44:48,241] - database: Connected to database was successfull
[INFO] [2025-04-15 16:44:48,770] - pages: 'Start' page was openned
[INFO] [2025-04-15 16:46:18,431] - main: App Started
[INFO] [2025-04-15 16:46:18,490] - database: Connected to database was successfull
[INFO] [2025-04-15 16:46:18,957] - pages: 'Start' page was openned
[ERROR] [2025-04-15 16:46:21,367] - asyncio: Future exception was never retrieved
future: <Future finished exception=ValueError('Must have exactly one of create/read/write/append mode and at most one plus')>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\core\page.py", line 903, in wrapper
    handler(*args)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\utilits_desktop.py", line 183, in pageClose
    with open("Admin Configure", '+') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Must have exactly one of create/read/write/append mode and at most one plus
[INFO] [2025-04-15 16:46:56,819] - main: App Started
[INFO] [2025-04-15 16:46:56,877] - database: Connected to database was successfull
[INFO] [2025-04-15 16:46:57,412] - pages: 'Start' page was openned
[INFO] [2025-04-15 16:47:24,080] - main: App Started
[INFO] [2025-04-15 16:47:24,132] - database: Connected to database was successfull
[INFO] [2025-04-15 16:47:24,662] - pages: 'Start' page was openned
[ERROR] [2025-04-15 16:47:42,537] - asyncio: Future exception was never retrieved
future: <Future finished exception=ValueError('I/O operation on closed file.')>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\core\page.py", line 903, in wrapper
    handler(*args)
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\utilits_desktop.py", line 184, in pageClose
    for line in file:
ValueError: I/O operation on closed file.
[INFO] [2025-04-15 17:06:14,672] - main: App Started
[INFO] [2025-04-15 17:06:14,725] - database: Connected to database was successfull
[INFO] [2025-04-15 17:06:31,372] - main: App Started
[INFO] [2025-04-15 17:06:31,424] - database: Connected to database was successfull
[INFO] [2025-04-15 17:07:31,117] - main: App Started
[INFO] [2025-04-15 17:07:31,256] - database: Connected to database was successfull
[INFO] [2025-04-15 17:07:43,925] - pages: 'Start' page was openned
[INFO] [2025-04-15 17:08:04,183] - main: App Started
[INFO] [2025-04-15 17:08:04,239] - database: Connected to database was successfull
[INFO] [2025-04-15 17:08:07,181] - pages: 'Start' page was openned
[INFO] [2025-04-15 17:08:51,448] - main: App Started
[INFO] [2025-04-15 17:08:51,501] - database: Connected to database was successfull
[INFO] [2025-04-15 17:08:51,966] - pages: 'Start' page was openned
[INFO] [2025-04-15 17:09:08,155] - main: App Started
[INFO] [2025-04-15 17:09:08,208] - database: Connected to database was successfull
[INFO] [2025-04-15 17:09:08,657] - pages: 'Start' page was openned
